INSERT INTO SONG (ARTISTNAME, TITLE) VALUES
('The Beatles', 'Hey Jude'),
('Adele', 'Someone Like You'),
('Ed Sheeran', 'Shape of You'),
('Elton John', 'Rocket Man'),
('Taylor Swift', 'Shake It Off'),
('Queen', 'Bohemian Rhapsody'),
('Bill Withers', 'Lean on Me'),
('John Legend', 'All of Me'),
('Bruno Mars', 'Uptown Funk'),
('Michael Jackson', 'Billie Jean'),
('The Rolling Stones', 'Paint It Black'),
('Ariana Grande', 'Thank U, Next'),
('Whitney Houston', 'I Will Always Love You'),
('Katy Perry', 'Firework'),
('Ed Sheeran', 'Perfect'),
('Imagine Dragons', 'Radioactive'),
('Lady Gaga', 'Bad Romance'),
('Beyoncé', 'Halo'),
('Sam Smith', 'Stay With Me'),
('Rihanna', 'Diamonds'),
('Drake', 'Hotline Bling'),
('Shakira', 'Hips Don’t Lie'),
('Maroon 5', 'Sugar'),
('Post Malone', 'Circles'),
('Coldplay', 'Fix You'),
('Taylor Swift', 'Love Story'),
('Sia', 'Chandelier'),
('The Weeknd', 'Blinding Lights'),
('Billie Eilish', 'Bad Guy'),
('Lizzo', 'Truth Hurts');

INSERT INTO KARAOKEFILE (SONGID, VERSION) VALUES
(1, 'Original'),
(1, 'Solo'),
(1, 'Remix'),
(2, 'Original'),
(2, 'Solo'),
(2, 'Duet'),
(3, 'Original'),
(3, 'Solo'),
(3, 'Trio'),
(4, 'Original'),
(4, 'Solo'),
(4, 'Extended'),
(5, 'Original'),
(5, 'Solo'),
(5, 'Extended'),
(6, 'Original'),
(6, 'Solo'),
(6, 'Remix'),
(7, 'Original'),
(7, 'Solo'),
(7, 'Duet'),
(8, 'Original'),
(8, 'Solo'),
(8, 'Trio'),
(9, 'Original'),
(9, 'Solo'),
(9, 'Remix'),
(10, 'Original'),
(10, 'Solo'),
(10, 'Duet'),
(11, 'Original'),
(11, 'Solo'),
(11, 'Extended'),
(12, 'Original'),
(12, 'Solo'),
(12, 'Remix'),
(13, 'Original'),
(13, 'Solo'),
(13, 'Duet'),
(14, 'Original'),
(14, 'Solo'),
(14, 'Trio'),
(15, 'Original'),
(15, 'Solo'),
(15, 'Extended'),
(16, 'Original'),
(16, 'Solo'),
(16, 'Duet'),
(17, 'Original'),
(17, 'Solo'),
(17, 'Remix'),
(18, 'Original'),
(18, 'Solo'),
(18, 'Trio'),
(19, 'Original'),
(19, 'Solo'),
(19, 'Duet'),
(20, 'Original'),
(20, 'Solo'),
(20, 'Extended'),
(21, 'Original'),
(21, 'Solo'),
(21, 'Duet'),
(22, 'Original'),
(22, 'Solo'),
(22, 'Extended'),
(23, 'Original'),
(23, 'Solo'),
(23, 'Trio'),
(24, 'Original'),
(24, 'Solo'),
(24, 'Remix'),
(25, 'Original'),
(25, 'Solo'),
(25, 'Duet'),
(26, 'Original'),
(26, 'Solo'),
(26, 'Extended'),
(27, 'Original'),
(27, 'Solo'),
(27, 'Remix'),
(28, 'Original'),
(28, 'Solo'),
(28, 'Duet'),
(29, 'Original'),
(29, 'Solo'),
(29, 'Extended'),
(30, 'Original'),
(30, 'Solo');



INSERT INTO CONTRIBUTOR (CNAME) VALUES 
('John Lennon'),
('Matt McCartney'),
('James Adams'),
('Ed Sheeran'),
('Taylor Swift'),
('Emmanuel Mercury'),
('Dean Withers'),
('John Legend'),
('Bruno Mars'),
('Michael Jackson'),
('Jagger Jones'),
('Ariana Grande'),
('Whitney Houston'),
('Katy Perry'),
('Ed Sheeran'),
('Imagine Dragons'),
('Lady Gaga'),
('Beyoncé Z'),
('Sam Smith'),
('Rihanna Fenty'),
('Drake Aubrey'),
('Shakira Ripoll'),
('Adam Levine'),
('Post Malone'),
('Sang Martin'),
('Taylor Swift'),
('Sia Furler'),
('The Weeknd'),
('Billie Eilish');

INSERT INTO CONTRIBUTE (SONGID, CONTRIBUTORID, CONTRIBUTIONTYPE) VALUES
(1, 1, 'Lyrics'),
(1, 2, 'Music'),
(2, 3, 'Lyrics'),
(2, 4, 'Music'),
(3, 5, 'Lyrics'),
(3, 6, 'Music'),
(4, 7, 'Lyrics'),
(4, 8, 'Music'),
(5, 9, 'Arrangement'),
(5, 10, 'Lyrics'),
(6, 11, 'Music'),
(6, 12, 'Arrangement'),
(7, 13, 'Lyrics'),
(7, 14, 'Music'),
(8, 15, 'Arrangement'),
(8, 16, 'Music'),
(9, 17, 'Lyrics'),
(9, 18, 'Music'),
(10, 19, 'Lyrics'),
(10, 20, 'Music'),
(11, 21, 'Arrangement'),
(11, 22, 'Lyrics'),
(12, 23, 'Music'),
(12, 24, 'Arrangement'),
(13, 25, 'Lyrics'),
(13, 26, 'Music'),
(14, 27, 'Arrangement'),
(14, 28, 'Lyrics'),
(15, 27, 'Music'),
(15, 21, 'Lyrics'),
(16, 1, 'Arrangement'),
(17, 2, 'Music'),
(18, 3, 'Arrangement'),
(19, 4, 'Lyrics'),
(20, 5, 'Music'),
(21, 6, 'Arrangement'),
(22, 7, 'Music'),
(23, 8, 'Lyrics'),
(24, 9, 'Arrangement'),
(25, 10, 'Music'),
(26, 11, 'Lyrics'),
(27, 12, 'Arrangement'),
(28, 13, 'Music'),
(29, 14, 'Lyrics'),
(30, 15, 'Arrangement');
